# Ingress 테스트 할때 사용하는 ip는 vagrant machine의 ip인 192.168.100.100을 해당 ip로 삼아서 도메인을 만들도록 한다
# http://v1.whoami.192.168.100.100.sslip.io/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami-v1
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: v1.whoami.192.168.100.100.sslip.io
    http:
      paths: 
      - path: /
        backend:
          serviceName: whoami-v1
          servicePort: 4567
